shiny:
  proxy:
    title: MilkyWay ShinyProxy
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 81
    authentication: none
    admin-groups: admin
    container-wait-time: 60000
    # Simple auth configuration
    users:
    - name: admin
      password: admin
      groups: admin
    - name: collaborators
      password: collaborators
      groups: collaborators
    # Docker configuration
    docker:
      cert-path: /home/none
      host: 127.0.0.1
      url: http://localhost:2375
      port-range-start: 20000
  apps:
  - name: milkyway
    display-name: MilkyWay Proteomics
    description: An interface to the Galaxy MilkyWay Workflow System
    docker-image: wbarshop/milkyway_shiny:latest
    docker-network: milkyway-stack_milkynet
    groups: scientists, collaborators, admin

logging:
  file:
    shinyproxy.log

